# Generated by Django 2.2.2 on 2019-06-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sanpham',
            fields=[
                ('idSP', models.IntegerField(max_length=10, primary_key='idSP', serialize=False)),
                ('idLoaiSP', models.IntegerField(max_length=11)),
                ('tenSP', models.CharField(max_length=100)),
                ('DonGia', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('GioiThieu', models.TextField()),
                ('GiamGia', models.IntegerField(max_length=11)),
                ('image_link', models.CharField(max_length=100)),
                ('image_list', models.TextField()),
                ('timeNhap', models.IntegerField(default=0, max_length=11)),
                ('luotxem', models.IntegerField(default=0, max_length=11)),
                ('SLTon', models.IntegerField(max_length=10)),
                ('idtin', models.IntegerField(max_length=10)),
            ],
        ),
    ]
