# Generated by Django 2.2.2 on 2019-06-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='GiamGia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='SLTon',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='idLoaiSP',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='idSP',
            field=models.IntegerField(primary_key='idSP', serialize=False),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='idtin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='luotxem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='timeNhap',
            field=models.IntegerField(default=0),
        ),
    ]
