# Generated by Django 2.2.2 on 2019-06-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190609_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='DonGia',
            field=models.FloatField(default=0),
        ),
    ]
